FROM node:12

# working directory
RUN mkdir /app
WORKDIR /app

# update the operting system
RUN apt-get update

# a wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# install node dependency and build project
RUN npm install

RUN mv ./src/openlane-run.sh ./build/src/

# container port
EXPOSE 8080
