scrape_configs:
    # Cadvisor for docker containers
    - job_name: cadvisor
      scrape_interval: 5s
      static_configs:
          - targets:
                - cadvisor:8080
    # SLURM resource manager:
#    - job_name: 'slurm_exporter'
#      scrape_interval: 30s
#      scrape_timeout: 30s
#      static_configs:
#          - targets: ['slurm_host.fqdn:3033']
